return {
   {
      type                = "real",
      name                = "VGA1",
      start_x             = 0,
      start_y             = 0,
      width               = 1920,
      height              = 1080,
      screen_real_index   = 3,
      screen_top_index    = 1,
      screen_right_index  = 2,
      screen_bottom_index = 2,
      screen_left_index   = 4
   },
   {
      type                = "real",
      name                = "eDP1",
      start_x             = 1920,
      start_y             = 0,
      width               = 1920,
      height              = 1080,
      screen_real_index   = 1,
      screen_top_index    = 5,
      screen_right_index  = 3,
      screen_bottom_index = 5,
      screen_left_index   = 1
   },
   {
      type                = "real",
      name                = "HDMI1",
      start_x             = 3840,
      start_y             = 0,
      width               = 1920,
      height              = 1080,
      screen_real_index   = 2,
      screen_top_index    = 3,
      screen_right_index  = 4,
      screen_bottom_index = 3,
      screen_left_index   = 2
   },
   {
      type                = "virtual",
      name                = "VIRTUAL1",
      password            = "19801308qqq",
      port                = 5900,
      start_x             = 5760,
      start_y             = 0,
      width               = 1280,
      height              = 1024,
      screen_real_index   = 4,
      screen_top_index    = 4,
      screen_right_index  = 1,
      screen_bottom_index = 4,
      screen_left_index   = 3
   },
   {
      type                = "virtual",
      name                = "VIRTUAL2",
      password            = "19801308qqq",
      port                = 5901,
      start_x             = 1920,
      start_y             = 1080,
      width               = 1280,
      height              = 736,
      screen_real_index   = 5,
      screen_top_index    = 2,
      screen_right_index  = 6,
      screen_bottom_index = 2,
      screen_left_index   = 6
   },
   {
      type                = "virtual",
      name                = "VIRTUAL3",
      password            = "19801308qqq",
      port                = 5902,
      start_x             = 3200,
      start_y             = 1080,
      width               = 1920,
      height              = 1080,
      screen_real_index   = 6,
      screen_top_index    = 2,
      screen_right_index  = 5,
      screen_bottom_index = 2,
      screen_left_index   = 5
   },
}
